# Generated by Django 3.0 on 2019-12-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
