# Generated by Django 3.0 on 2019-12-19 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mir', '0002_post1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('parentage', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(max_length=12)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
