# Generated by Django 3.0 on 2019-12-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mir', '0003_auto_20191219_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
