# Generated by Django 3.0 on 2019-12-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir', '0004_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('parentage', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('reg_date', models.CharField(max_length=50)),
            ],
        ),
    ]
